[package]
name = "aitalked"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.9"
encoding_rs = "0.8"
derivative = "2"
once_cell = "1"
bitflags = "2"
